// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irukapvnsuitosmppjpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlydWthcHZuc3VpdG9zbXBwanBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMzczNTgsImV4cCI6MjA2ODcxMzM1OH0.O5csPDp5JomYailYrH0GdmB3SpLcprEd5SgYUNtyCeE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});